/* 
  1. If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
  Find the sum of all the multiples of 3 or 5 below 1000.
*/
const SumMult3or5 = (n) => {
  let sum = 0
  for(let i = 0; i < n; i++) {
    if(i % 3 === 0 || i % 5 === 0) sum += i
  }
  return sum
}
// console.log(SumMult3or5(1000))
// ANSWER: 233168



/*
  2. Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
const evenFibNums = () => {
  let num1 = 0, num2 = 1, next = 0, sum = 0
  function fib() {
    next = num1 + num2
    num1 = num2
    num2 = next
    next % 2 === 0 ? sum += next : sum += 0
  }
  while(next <= 4000000) fib()
  return sum
}
// console.log(evenFibNums())
// ANSWER: 4613732



/*
  3.The prime factors of 13195 are 5, 7, 13 and 29.
  What is the largest prime factor of the number 600851475143 ?
*/
const largestPrimeFactor = (num) => {
  let primes = findPrimes(12345)
  let primeFactors = []

  let i = 0
  let temp = num

  while(
    primeFactors.reduce(
      (prev, curr) => prev * curr, 1
    ) !== num) {
    if(temp % primes[i] === 0) {
      temp /= primes[i]
      primeFactors.push(primes[i])
    } else {
      i++
    } 
  }

  function findPrimes(n) {
    let primes = [2]
    for(let i = 3; i <= n; i++){
      if(((i / 2) % 2 !== 0)) {
        let check = true
        primes.forEach(prime => {
          if(i % prime === 0) check = false 
        })
        if(check) primes.push(i)
      }
    }
    return primes
  }

  return Math.max(...primeFactors)
}
// console.log(largestPrimeFactor((600851475143)))
// ANSWER: 6857



/*
  4. A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
  Find the largest palindrome made from the product of two 3-digit numbers.
*/
const largestPalindromeNumber = () => {
  let high = 0
  for(let i = 999; i > 800; i--) {
    for(let j = 999; j > 800; j--) {
      let temp = (i*j).toLocaleString().split('')
      if(temp[0] === temp[6] && temp[1] === temp[5] && temp[2] === temp[4]) {
        if((i * j) > high) high = i * j
      }
    }
  }
  return high
}
// console.log(largestPalindromeNumber())
// ANSWER: 906,609 from [993, 913]